### ISSUE TITLE
Make a command that will only put the message in chat.

### ISSUE THREAD

**Issue by pulcher** [pulcher/TalkingHead#52]

**Comment by pulcher** [comment]
This is so he can create hit own commands:

Example: NightBot would understand this: $(twitch.tv/haroldpulcher "{{uptimeLength}}")

**Comment by B0tzerker** [comment]
At the time I requested this command in chat, there were no mods in chat. There was no uptime command and I had assumed mrbigheadbot was nightbot (thinking you renamed nightbot.) Since I am not a mod in your channel, I wondered if I could force MBH to type the code in chat which would create the uptime command. The nightbot chat code is
__!addcom !uptime The channel has been live since: $(twitch.tv/haroldpulcher "{{uptimeLength}}")__
Unfortunately there's no nightbot so the chat code would not work. Typically streamers have one or two bots in their channel (nightbot or moobot) and streamlabs bot. These bots provide default commands as well as the ability for the streamer and mods to create new commands. These bots also provide the streamer with additional functionality such as Metrics tracking, TextToSpeech, and new avenues for donations.
